/**
 * Phase 17POS-AUTH-A3 — pure tests confirming the approval-code gate on
 * deletePaymentRecord / reopenSessionForPayment does NOT change the
 * underlying role permission model. No DB access — the actual gated
 * mutations (lib/actions/history.ts) require a live payment row and are
 * covered by manual UAT (see docs/uat/UAT_SCRIPTS.md), not here.
 * Runner: node:test via tsx — `npm run test:approval-code`.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { can } from '../../lib/auth/permissions';
import { isSelfApprovalAllowed } from '../../lib/auth/approval-code-core';

describe('payment:delete permission — owner only (unchanged by A3)', () => {
  it('owner can delete a payment', () => {
    assert.equal(can('owner', 'payment:delete'), true);
  });
  it('manager cannot delete a payment', () => {
    assert.equal(can('manager', 'payment:delete'), false);
  });
  it('cashier cannot delete a payment', () => {
    assert.equal(can('cashier', 'payment:delete'), false);
  });
  it('kitchen cannot delete a payment', () => {
    assert.equal(can('kitchen', 'payment:delete'), false);
  });
});

describe('payment:reopen permission — owner + manager only (unchanged by A3)', () => {
  it('owner can reopen a payment', () => {
    assert.equal(can('owner', 'payment:reopen'), true);
  });
  it('manager can reopen a payment', () => {
    assert.equal(can('manager', 'payment:reopen'), true);
  });
  it('cashier cannot reopen a payment', () => {
    assert.equal(can('cashier', 'payment:reopen'), false);
  });
  it('kitchen cannot reopen a payment', () => {
    assert.equal(can('kitchen', 'payment:reopen'), false);
  });
});

describe('approval code never expands permission — a manager holding a valid code still fails the payment:delete check upstream', () => {
  it('manager is not in the delete-permission set regardless of code validity (the code check in history.ts runs strictly after can())', () => {
    assert.equal(can('manager', 'payment:delete'), false);
  });
  it('cashier is not in the delete- or reopen-permission sets regardless of code validity', () => {
    assert.equal(can('cashier', 'payment:delete'), false);
    assert.equal(can('cashier', 'payment:reopen'), false);
  });
});

describe('self-approval policy applies unchanged to owner delete/reopen (A2C, reused as-is)', () => {
  const GENERATOR = 'owner-user-id';
  it('owner may redeem its own code to delete/reopen', () => {
    assert.equal(isSelfApprovalAllowed('owner', GENERATOR, GENERATOR), true);
  });
  it('manager may not redeem its own code to reopen', () => {
    assert.equal(isSelfApprovalAllowed('manager', GENERATOR, GENERATOR), false);
  });
  it('manager may redeem a code generated by someone else (e.g. owner) to reopen', () => {
    assert.equal(isSelfApprovalAllowed('manager', GENERATOR, 'manager-user-id'), true);
  });
});
