/**
 * Phase 17POS-AUTH-A2C — pure tests for the self-approval policy:
 * owner may redeem a code it generated itself; manager/cashier may not.
 * No DB access — covers isSelfApprovalAllowed() only. The full consumption
 * flow (DB lookup, hash compare, atomic UPDATE) in
 * lib/actions/manager-approval.ts is intentionally not covered here (no DB
 * test harness in this project).
 * Runner: node:test via tsx — `npm run test:approval-code`.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  isSelfApprovalAllowed,
  APPROVAL_CODE_SELF_APPROVAL_REJECT_MESSAGE,
  APPROVAL_CODE_REJECT_MESSAGE,
} from '../../lib/auth/approval-code-core';

const GENERATOR = 'user-aaa';
const OTHER_USER = 'user-bbb';

describe('isSelfApprovalAllowed', () => {
  it('A. owner self-approval is allowed', () => {
    assert.equal(isSelfApprovalAllowed('owner', GENERATOR, GENERATOR), true);
  });

  it('B. manager self-approval is rejected', () => {
    assert.equal(isSelfApprovalAllowed('manager', GENERATOR, GENERATOR), false);
  });

  it('C. cashier self-approval is rejected (defense in depth — should be structurally impossible since cashier cannot generate codes)', () => {
    assert.equal(isSelfApprovalAllowed('cashier', GENERATOR, GENERATOR), false);
  });

  it('an unrecognized role is rejected on self-approval (fail closed, not open)', () => {
    assert.equal(isSelfApprovalAllowed('kitchen', GENERATOR, GENERATOR), false);
  });

  it('D. manager using a code generated by someone else (e.g. owner) is allowed', () => {
    assert.equal(isSelfApprovalAllowed('manager', GENERATOR, OTHER_USER), true);
  });

  it('E. cashier using a code generated by manager/owner is allowed', () => {
    assert.equal(isSelfApprovalAllowed('cashier', GENERATOR, OTHER_USER), true);
  });

  it('owner using a code generated by someone else is also allowed (not-self is always fine)', () => {
    assert.equal(isSelfApprovalAllowed('owner', GENERATOR, OTHER_USER), true);
  });
});

describe('self-approval rejection message', () => {
  it('is distinct from the generic invalid-code message', () => {
    assert.notEqual(APPROVAL_CODE_SELF_APPROVAL_REJECT_MESSAGE, APPROVAL_CODE_REJECT_MESSAGE);
  });

  it('never embeds a plaintext-looking 6-character code', () => {
    assert.doesNotMatch(APPROVAL_CODE_SELF_APPROVAL_REJECT_MESSAGE, /[A-Z0-9]{6}/);
  });

  it('matches the exact Thai wording specified for the phase', () => {
    assert.equal(
      APPROVAL_CODE_SELF_APPROVAL_REJECT_MESSAGE,
      'ไม่สามารถใช้รหัสที่คุณสร้างเองได้ กรุณาให้ผู้จัดการหรือเจ้าของสร้างรหัสใหม่',
    );
  });
});
